baseURL = "/"
title = "Redis"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
# theme = []

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


[related]
[[related.indices]]
  name = 'group'
  weight = 1
  includeNewer = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[params]
  tagManagerId = "GTM-T4MTBKP"

# Language configuration

[languages]

[languages.en]
title = "Redis"
description = "Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache, and message broker"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "RSS"] # print

[menu]
  [[menu.main]]
    identifier = "get-started"
    name = "GET STARTED"
    weight = 1
  [[menu.main]]
    identifier = "redis"
    name = "REDIS"
    url = "/docs/getting-started/"
    parent = "get-started"
    weight = 1
  [[menu.main]]
    identifier = "redis-stack"
    name = "REDIS STACK"
    url = "/docs/stack/get-started/"
    parent = "get-started"
    weight = 2
  [[menu.main]]
    identifier = "docs"
    name = "DOCS"
    url = "/docs/"
    weight = 2
  [[menu.main]]
    identifier = "commands"
    name = "COMMANDS"
    url = "/commands/"
    weight = 3
  [[menu.main]]
    identifier = "resources"
    name = "RESOURCES"
    weight = 4
  [[menu.main]]
    identifier = "resource-download"
    name = "DOWNLOAD"
    url = "/download/"
    parent = "resources"
    weight = 1
  [[menu.main]]
    identifier = "support"
    name = "SUPPORT"
    url = "/support/"
    parent = "resources"
    weight = 2
  [[menu.main]]
    identifier = "clients"
    name = "CLIENTS"
    url = "/docs/clients/"
    parent = "resources"
    weight = 3
  [[menu.main]]
    identifier = "community"
    name = "COMMUNITY"
    url = "/community/"
    weight = 5
  [[menu.buttons]]
    identifier = "download"
    name = "DOWNLOAD"
    url = "/download/"
    weight = 1
  [[menu.buttons]]
    identifier = "try-free"
    name = "TRY REDIS CLOUD"
    url = "http://redis.com/try-free/"
    weight = 2
    [menu.buttons.params]
      style = "outline-white"
