scheme = [ "http", "https" ]

exclude = [
    "github.com/.*/.*/issues/new.*",
    "github.com/.*/.*/edit/.*",
    "twitter.com",
    "googletagmanager.com",
    "packages.redis.io",
    "techstacks.io",
    "sciencedirect.com",
    "localhost",
    "127.0.0.1"
]

exclude_path = [
    "public/resources/clients/index.html",
    "public/resources/libraries/index.html",
    "public/resources/modules/index.html",
    "public/resources/tools/index.html"
]

timeout = 10

user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
