[context.production]
  command = "make netlify"
  publish = "public"
  [context.production.environment]
    ENV = "production"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"

[context.development]
  command = "make netlify"
  publish = "public"
  [context.development.environment]
    ENV = "development"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"

[context.branch-deploy]
  command = "make netlify"
  publish = "public"
  [context.branch-deploy.environment]
    ENV = "development"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"

[context.preview]
  command = "make netlify"
  publish = "public"
  [context.preview.environment]
    ENV = "preview"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"