[context.production]
  command = "make netlify"
  publish = "public"
  [context.production.environment]
    ENV = "production"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"
    HUGO_VERSION = "0.108.0"

[context.development]
  command = "make netlify"
  publish = "public"
  [context.development.environment]
    ENV = "development"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"
    HUGO_VERSION = "0.108.0"

[context.branch-deploy]
  command = "make netlify"
  publish = "public"
  [context.branch-deploy.environment]
    ENV = "development"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"
    HUGO_VERSION = "0.108.0"

[context.deploy-preview]
  command = "make netlify"
  publish = "public"
  [context.deploy-preview.environment]
    ENV = "deploy-preview"
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"
    HUGO_VERSION = "0.108.0"
